http://localhost:8080/api/healthz

###

POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
    "body": "esto es una prueba"
}

###

POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
  "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

###

POST http://localhost:8080/api/validate_chirp
content-type: application/json

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate",
  "extra": "this should be ignored"
}

###

POST http://localhost:8080/api/users
content-type: application/json

{
  "email": "matias@prueba.com"
}

###

POST http://localhost:8080/api/users
content-type: application/json

{
  "email": "astrid@prueba.com"
}

###

POST http://localhost:8080/admin/reset

###

POST http://localhost:8080/api/chirps
content-type: application/json

{
  "body": "My second chirp",
  "user_id": "4aef11d1-7dee-40bc-8bbb-99cb9324b583"
}